export default {
  CREATE_REQUEST: 'CREATE_REQUEST',
  CURRENT_REQUEST: 'CURRENT_REQUEST',
  LOAD_REQUESTS: 'LOAD_REQUESTS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  DELETE_REQUEST: 'DELETE_REQUEST',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER'
};
